### ISSUE TITLE
node v0.12

### ISSUE THREAD

**Issue by rashfael** [creatale/node-dv#17]
Node v0.12 brings a new version of v8 (which is a good thing), which in turn breaks a lot of C++ apis ([see here](http://strongloop.com/strongblog/node-js-v0-12-c-apis-breaking/)).

We probably should migrate the code in the near future and advice users who still run older node.js versions to keep using the current version of dv.

**Comment by WolfgangFellger** [comment]
Looks like we basically have the option to port the code to Node 0.12 or to NAN (https://www.npmjs.com/package/nan). The first seems slightly easier, but would break Node 0.10 compatibility from that version onwards.

Is anybody currently using node-dv bound to Node 0.10?

**Comment by v4l3r10** [comment]
I use >0.11 :)  :+1:  for porting to 0.12

**Comment by omega32** [comment]
Using NAN may be better in the long run. It may be more work now, but should make things easier going forward.

**Comment by ele828** [comment]
I use Node 0.12. I hope author can update DV in a few days

**Comment by WolfgangFellger** [comment]
I will probably go with NAN. Unfortunately, finding the time has proven to be nontrivial.

**Comment by ele828** [comment]
Yeah, I will appreciate it. Anyway, dv helps me a lot.Thanks

**Comment by AntJanus** [comment]
Thanks guys! I'm stuck on v0.10.33, and I'd love to upgrade since there are some new features that 0.12 has that I'd like to use :)

**Comment by rashfael** [comment]
node-dv is now compatible with both 0.10 and 0.12 by way of NAN. It should also work with io.js, although we didn't test that.

**Comment by AntJanus** [comment]
YAY! =D
