### ISSUE TITLE
Is it possible to scan a music score with this?

### ISSUE THREAD

**Issue by IonicaBizau** [creatale/node-dv#20]
Having a music score, is it possible to get the notes in a programmatic format?

**Comment by ele828** [comment]
Is the score showing in a vision way? If it is, use node-dv is ok! :P

**Comment by WolfgangFellger** [comment]
No; not in any form that a score would come out.

The image processing part of this library may however be useful if you want to implement it yourself (e.g. "find a group of five horizontal lines, then find round blobs in relation to it, then interpret that").

**Comment by IonicaBizau** [comment]
Ok, thanks! :+1:

**Comment by WolfgangFellger** [comment]
The above is of course a blatant oversimplification. Seeing the amount of info that has to go *into* a score (e.g. LilyPond), this will probably deserve its own project.

**Comment by ele828** [comment]
Sorry for that, I misunderstand the word "music score"   Hope u solve it soon

**Comment by IonicaBizau** [comment]
No problem, I ended by using MuseScore experimental service for that. It gives me an XML which I convert into my JSON format. :smile:
