### ISSUE TITLE
Add helper error message if new omitted

### ISSUE THREAD

**Issue by robertkeizer** [creatale/node-dv#22]
Spent way to long with the error `Assertion failed: (handle->InternalFieldCount() > 0), function Wrap, file /Users/robertkeizer/.node-gyp/0.12.2/src/node_object_wrap.h, line 77.`.

Stupid mistake on my part, I was doing ` var x = dv.Image( "png", fs.readFileSync( "path/to/file.png" ) );`, instead of `var x = new dv.Image ...`.

Would be helpful if the package spit out an error telling people they were being dumb.

**Comment by WolfgangFellger** [comment]
This will be fixed for the upgrade to Nan 2 (see #27).

`Image()` now simply delegates to `new Image()`.
