### ISSUE TITLE
g++: internal compiler error: Killed (program cc1plus)

### ISSUE THREAD

**Issue by dazziola** [creatale/node-dv#23]
I keep hitting an error when trying to install using the **npm install dv** command on Ubuntu 14.04.

      CXX(target) Release/obj.target/libopencv/deps/opencv/modules/core/src/matrix.o
      g++: internal compiler error: Killed (program cc1plus)
      Please submit a full bug report,
      with preprocessed source if appropriate.
      See <file:///usr/share/doc/gcc-4.9/README.Bugs> for instructions.
      deps/opencv/libopencv.target.mk:158: recipe for target    'Release/obj.target/libopencv/deps/opencv/modules/core/src/matrix.o' failed
    make: *** [Release/obj.target/libopencv/deps/opencv/modules/core/src/matrix.o] Error 4
    make: Leaving directory '/home/darraghflynn/node_modules/dv/build'
    gyp ERR! build error 
    gyp ERR! stack Error: `make` failed with exit code: 2
    gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
    gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
    gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:810:12)
    gyp ERR! System Linux 3.16.0-28-generic
    gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
    gyp ERR! cwd /home/darraghflynn/node_modules/dv
    gyp ERR! node -v v0.10.33
    gyp ERR! node-gyp -v v1.0.1
    gyp ERR! not ok

**Comment by WolfgangFellger** [comment]
The 'killed' may indicate the Out Of Memory Killer has struck, which means you simply have too little RAM. Please check your dmesg after the error.

Did you specifiy any multi-compilation options (e.g environment variable JOBS)? You may also try the command `node-gyp build` in the half-installed dv folder, this should continue the compilation freshly from this individual file.

**Comment by dazziola** [comment]
This would make sense WolfGang. I tried to install it on a DigitalOcean box with 512mb RAM, seemed to install fine on my Mac (16gb RAM!) and is working fine locally.

Just checked dmesg and sure enough:
    
    [2934602.811157] Out of memory: Kill process 17728 (cc1plus) score 331 or sacrifice child

Thanks for the prompt message!

**Comment by dazziola** [comment]
Actually, just as a question, how much RAM is required to install and run the DV? It looks like a seriously powerful tool when up and running.

**Comment by WolfgangFellger** [comment]
I do not know. I'm regularly compiling it with four processes on a 6 GB machine, so I'd estimate somewhere between one and two GB. And about the same to reasonable use it (depends on what you're doing of course).

I'd be glad if you could gradually ramp up your swap space and report back!

**Comment by dazziola** [comment]
If I can justify the extra $5 a month spend on the VPS I will let you know for sure! That would bump my box upto 1GB of RAM which should be enough to compile hopefully. 512mb just doesn't cut it in this day and age!

**Comment by dazziola** [comment]
Just bumped my VPS up to 1GB of RAM, same processor speed and boom, it installed fine on Ubuntu 14.04, thanks for all the great work of this software!
