### ISSUE TITLE
tesseract.tessedit_char_whitelist not working with umlauten

### ISSUE THREAD

**Issue by HansHammel** [creatale/node-dv#24]
German "Umlaute" (ö,ä,ü,ß,Ö,Ä,Ü) seem to be ignored by the tessedit_char_whitelist option.

**Comment by WolfgangFellger** [comment]
That is pretty much our use case, and it's working here... Can you give a complete example?

Shots in the dark: Are you using the 'deu' language file? Apart from that, I could imagine a hiccup if your source is not UTF-8-encoded, please check that.
