### ISSUE TITLE
Does not work in Node 4

### ISSUE THREAD

**Issue by WolfgangFellger** [creatale/node-dv#27]
Well, I am a bit surprised nobody complained yet :)

Background: We need to upgrade to Nan 2 for this, which is a large undertaking. Unfortunately we have enough accumulated cruft that the [automated converter from nodesource](https://github.com/nodesource/upgrade-utils) isn't enough.

Good news though: I have started to port it over, and followed the Nan "best practices" more strictly this time. There is already something compiling and running in the nan2 branch. Xzing is still missing, and no guarantees on memory leaks.

It may be some time before can I finalize this. Crash reports are welcome :)

**Comment by spirospolitis** [comment]
I am complaining :-) 

Node v4.1.1. and npm install dv fails.

**Comment by WolfgangFellger** [comment]
Well, yes. If you are brave, you may try the nan2 branch. `Image` and `Tesseract` are already working, and I've checked that it works in Node 4 and 0.12 (i.e. compiles and tests run).

Unfortunately, I won't have time to continue on this at least until Wednesday.

**Comment by WolfgangFellger** [comment]
I just released 1.10.0. A couple other things came up while looking through the code, so this is a somewhat large release. See the changelog.
