### ISSUE TITLE
Failing to install node-dv at 'node-gyp rebuild'

### ISSUE THREAD

**Issue by peternoordijk** [creatale/node-dv#28]
When running the command ```npm install dv --save``` I encountered an error when running the child process ```node-gyp rebuild```.

See the following logs: [message.txt](https://docs.google.com/document/d/1QVTi2EI0NhS7jZaCaQj11OijBL6QLJJGnFhWqlIue2w/edit?usp=sharing) [error.txt](https://docs.google.com/document/d/1DKcFnMXtubaS81zGp1h0yKKy9vGUMox8z8ZDFm_4iI4/edit?usp=sharing)

I tried this on two different Windows (10) computers. Thanks in advance :smile:

**Comment by WolfgangFellger** [comment]
The good old issue of "windef.h defines min and max macros" strikes again. Fixed in 1.10.1.

**Comment by WolfgangFellger** [comment]
I assume this is working for you as well?

**Comment by peternoordijk** [comment]
Yes it does, thank you very much for the quick fix!
